services:
  - type: web
    name: college-coding-platform-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PISTON_API_URL
        value: https://emkc.org/api/v2/piston
      - key: CORS_ORIGINS
        value: "*"
